In [9]:
import pandas as pd
df = pd.read_csv('placement.csv')

# ✅ 1. Using scipy.stats.zscore (Most Common)

In [12]:
from scipy import stats
import numpy as np
import pandas as pd

# Calculate Z-scores
df['z_score'] = np.abs(stats.zscore(df['cgpa']))

# Detect outliers (|z| > 3)
outliers = df[df['z_score'] > 3]
print(outliers)

     cgpa  placement_exam_marks  placed   z_score
485  4.92                  44.0       1  3.315909
995  8.87                  44.0       1  3.100701
996  9.12                  65.0       1  3.506815
997  4.89                  34.0       0  3.364643
999  4.90                  10.0       1  3.348398

# ✅ 2. Using statsmodels.robust.scale.mad (for Modified Z-score)

For data that is not normally distributed, use the Modified Z-score based on Median Absolute Deviation (MAD):

In [20]:
from statsmodels.robust.scale import mad

# Calculate modified Z-score manually
median = df['cgpa'].median()
mad_val = mad(df['cgpa'])
df['mod_z_score'] = 0.6745 * (df['cgpa'] - median) / mad_val

# Detect outliers
df[np.abs(df['mod_z_score']) > 3.5]

Empty DataFrame
Columns: [cgpa, placement_exam_marks, placed, z_score, mod_z_score]
Index: []

# ✅ 3. Using sklearn.preprocessing.StandardScaler (for scaling, not directly outlier detection)

In [25]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df['z_scaled'] = np.abs(scaler.fit_transform(df[['cgpa']]))
df[df['z_scaled'] > 3]

     cgpa  placement_exam_marks  placed   z_score  mod_z_score  z_scaled
485  4.92                  44.0       1  3.315909    -2.263621  3.315909
995  8.87                  44.0       1  3.100701     2.119370  3.100701
996  9.12                  65.0       1  3.506815     2.396775  3.506815
997  4.89                  34.0       0  3.364643    -2.296909  3.364643
999  4.90                  10.0       1  3.348398    -2.285813  3.348398