In [1]:
import pandas as pd
import numpy as np
from sklearn.experimental import enable_iterative_imputer  # Needed to enable it
from sklearn.impute import IterativeImputer

In [7]:
# # Sample DataFrame with missing values
# df = pd.DataFrame({
#     'A': [1, 2, np.nan, 4],
#     'B': [np.nan, 2, 3, 4],
#     'C': [5, 6, np.nan, 8]
# })
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9)
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [32]:
df = df.iloc[:,0:-1]

df.iloc[1,0] = np.NaN
df.iloc[3,1] = np.NaN
df.iloc[-1,-1] = np.NaN

C:\Users\parvez\AppData\Local\Temp\ipykernel_3844\644316641.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.NaN
C:\Users\parvez\AppData\Local\Temp\ipykernel_3844\644316641.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.NaN
C:\Users\parvez\AppData\Local\Temp\ipykernel_3844\644316641.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1] = np.NaN

In [34]:
df

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        NaN             5.0             20.0
2        15.0            10.0             41.0
14       12.0             NaN             26.0
44        2.0            15.0              NaN

In [36]:
# Create IterativeImputer object
imputer = IterativeImputer(random_state=0)

In [38]:
# Fit and transform the data
df_imputed = imputer.fit_transform(df)

In [40]:
# Convert back to DataFrame
df_imputed = pd.DataFrame(df_imputed, columns=df.columns)

In [42]:
df_imputed

   R&D Spend  Administration  Marketing Spend
0   8.000000       15.000000        30.000000
1  10.712222        5.000000        20.000000
2  15.000000       10.000000        41.000000
3  12.000000        6.328063        26.000000
4   2.000000       15.000000        12.990453