In [111]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [113]:
df1 = pd.read_csv("50_Startups.csv")

In [115]:
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9)
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [117]:
df.head(10)

    R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [119]:
df = df.iloc[:,0:-1]
df

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        4.0             5.0             20.0
2        15.0            10.0             41.0
14       12.0            16.0             26.0
44        2.0            15.0              3.0

In [121]:
df.iloc[1,0] = np.NaN
df.iloc[3,1] = np.NaN
df.iloc[-1,-1] = np.NaN

C:\Users\parvez\AppData\Local\Temp\ipykernel_7256\2040708130.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.NaN
C:\Users\parvez\AppData\Local\Temp\ipykernel_7256\2040708130.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.NaN
C:\Users\parvez\AppData\Local\Temp\ipykernel_7256\2040708130.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1] = np.NaN

In [123]:
df.head()

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        NaN             5.0             20.0
2        15.0            10.0             41.0
14       12.0             NaN             26.0
44        2.0            15.0              NaN

In [125]:
df.isnull().sum()

R&D Spend          1
Administration     1
Marketing Spend    1
dtype: int64

# Step 1 - Impute all missing values with mean of respective col

In [128]:
df0 = pd.DataFrame()
df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

# 0th Iteration

In [134]:
df0

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37       9.25            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [136]:
# Remove the col1 imputed value
df1 = df0.copy()
df1.iloc[1,0] = np.NaN
df1

    R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.25            26.00
44        2.0           15.00            29.25

In [138]:
# Use first 4 rows to build a model and use the last for prediction

X = df1.iloc[[0,2,3,4],1:3]
X

    Administration  Marketing Spend
21           15.00            30.00
2            10.00            41.00
14           11.25            26.00
44           15.00            29.25

In [140]:
y = df1.iloc[[0,2,3,4],0]
y

21     8.0
2     15.0
14    12.0
44     2.0
Name: R&D Spend, dtype: float64

In [142]:
lr = LinearRegression()
lr.fit(X,y)
vl = lr.predict(df1.iloc[1,1:].values.reshape(1,2))

C:\Users\parvez\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [144]:
df1.iloc[1,0] = vl

In [146]:
df1

    R&D Spend  Administration  Marketing Spend
21   8.000000           15.00            30.00
37  23.141587            5.00            20.00
2   15.000000           10.00            41.00
14  12.000000           11.25            26.00
44   2.000000           15.00            29.25

In [148]:
# Remove the col2 imputed value

df1.iloc[3,1] = np.NaN
df1

    R&D Spend  Administration  Marketing Spend
21   8.000000            15.0            30.00
37  23.141587             5.0            20.00
2   15.000000            10.0            41.00
14  12.000000             NaN            26.00
44   2.000000            15.0            29.25

In [150]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[[0,1,2,4],[0,2]]
X

y = df1.iloc[[0,1,2,4],[1]]
y

    Administration
21            15.0
37             5.0
2             10.0
44            15.0

In [152]:
lr = LinearRegression()
lr.fit(X,y)
vl = lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\parvez\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [154]:
df1.iloc[3,1] = vl

In [156]:
df1

    R&D Spend  Administration  Marketing Spend
21   8.000000       15.000000            30.00
37  23.141587        5.000000            20.00
2   15.000000       10.000000            41.00
14  12.000000       11.063618            26.00
44   2.000000       15.000000            29.25

In [158]:
# Remove the col3 imputed value
df1.iloc[4,-1] = np.NaN
df1

    R&D Spend  Administration  Marketing Spend
21   8.000000       15.000000             30.0
37  23.141587        5.000000             20.0
2   15.000000       10.000000             41.0
14  12.000000       11.063618             26.0
44   2.000000       15.000000              NaN

In [160]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[0:4,0:2]
X

    R&D Spend  Administration
21   8.000000       15.000000
37  23.141587        5.000000
2   15.000000       10.000000
14  12.000000       11.063618

In [162]:
y = df1.iloc[0:4,-1]
y

21    30.0
37    20.0
2     41.0
14    26.0
Name: Marketing Spend, dtype: float64

In [164]:
lr = LinearRegression()
lr.fit(X,y)
vl = lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

C:\Users\parvez\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [166]:
df1.iloc[4,-1] = vl

In [168]:
df1

    R&D Spend  Administration  Marketing Spend
21   8.000000       15.000000        30.000000
37  23.141587        5.000000        20.000000
2   15.000000       10.000000        41.000000
14  12.000000       11.063618        26.000000
44   2.000000       15.000000        31.601847

In [170]:
# Subtract 0th iteration from 1st iteration

df1 - df0

    R&D Spend  Administration  Marketing Spend
21   0.000000        0.000000         0.000000
37  13.891587        0.000000         0.000000
2    0.000000        0.000000         0.000000
14   0.000000       -0.186382         0.000000
44   0.000000        0.000000         2.351847

# 1st iteration

In [173]:
df2 = df1.copy()
df2.iloc[1,0] = np.NaN
df2

    R&D Spend  Administration  Marketing Spend
21        8.0       15.000000        30.000000
37        NaN        5.000000        20.000000
2        15.0       10.000000        41.000000
14       12.0       11.063618        26.000000
44        2.0       15.000000        31.601847

In [178]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
vl1=lr.predict(df2.iloc[1,1:].values.reshape(1,2))

C:\Users\parvez\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [180]:
df2.iloc[1,0] = vl1

In [182]:
df2

    R&D Spend  Administration  Marketing Spend
21   8.000000       15.000000        30.000000
37  23.828703        5.000000        20.000000
2   15.000000       10.000000        41.000000
14  12.000000       11.063618        26.000000
44   2.000000       15.000000        31.601847

In [184]:
df2.iloc[3,1] = np.NaN
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
df2.iloc[3,1] = lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\parvez\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [186]:
df2

    R&D Spend  Administration  Marketing Spend
21   8.000000       15.000000        30.000000
37  23.828703        5.000000        20.000000
2   15.000000       10.000000        41.000000
14  12.000000       11.230737        26.000000
44   2.000000       15.000000        31.601847

In [190]:
df2.iloc[4,-1] = np.NaN

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
df2.iloc[4,-1] = lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

C:\Users\parvez\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [192]:
df2

    R&D Spend  Administration  Marketing Spend
21   8.000000       15.000000        30.000000
37  23.828703        5.000000        20.000000
2   15.000000       10.000000        41.000000
14  12.000000       11.230737        26.000000
44   2.000000       15.000000        39.390436

In [194]:
df2 - df1

    R&D Spend  Administration  Marketing Spend
21   0.000000        0.000000         0.000000
37   0.687117        0.000000         0.000000
2    0.000000        0.000000         0.000000
14   0.000000        0.167119         0.000000
44   0.000000        0.000000         7.788589

# 2nd Iteration

In [197]:
df3 = df2.copy()
df3.iloc[1,0] = np.NaN
df3

    R&D Spend  Administration  Marketing Spend
21        8.0       15.000000        30.000000
37        NaN        5.000000        20.000000
2        15.0       10.000000        41.000000
14       12.0       11.230737        26.000000
44        2.0       15.000000        39.390436

In [199]:
X = df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

C:\Users\parvez\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([26.88778376])

In [201]:
df3.iloc[1,0] = lr.predict(df3.iloc[1,1:].values.reshape(1,2))

C:\Users\parvez\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [203]:
df3

    R&D Spend  Administration  Marketing Spend
21   8.000000       15.000000        30.000000
37  26.887784        5.000000        20.000000
2   15.000000       10.000000        41.000000
14  12.000000       11.230737        26.000000
44   2.000000       15.000000        39.390436

In [205]:
df3.iloc[3,1] = np.NaN
X = df3.iloc[[0,1,2,4],[0,2]]
y = df3.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\parvez\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([12.27579771])

In [207]:
df3.iloc[3,1] = lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\parvez\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [209]:
df3

    R&D Spend  Administration  Marketing Spend
21   8.000000       15.000000        30.000000
37  26.887784        5.000000        20.000000
2   15.000000       10.000000        41.000000
14  12.000000       12.275798        26.000000
44   2.000000       15.000000        39.390436

In [211]:
df3.iloc[4,-1] = np.NaN

X = df3.iloc[0:4,0:2]
y = df3.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

C:\Users\parvez\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([63.33935672])

In [213]:
df3.iloc[4,-1] = lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

C:\Users\parvez\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [215]:
df3

    R&D Spend  Administration  Marketing Spend
21   8.000000       15.000000        30.000000
37  26.887784        5.000000        20.000000
2   15.000000       10.000000        41.000000
14  12.000000       12.275798        26.000000
44   2.000000       15.000000        63.339357

In [217]:
df3 - df2

    R&D Spend  Administration  Marketing Spend
21    0.00000         0.00000          0.00000
37    3.05908         0.00000          0.00000
2     0.00000         0.00000          0.00000
14    0.00000         1.04506          0.00000
44    0.00000         0.00000         23.94892